# Generated by Django 4.0 on 2022-01-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=30)),
                ('Task_Description', models.TextField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
