# Generated by Django 4.0.2 on 2022-02-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactuser',
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
