# Generated by Django 4.0.2 on 2022-02-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
